# Generated by Django 5.1 on 2024-10-17 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('series_id', models.CharField(max_length=50, unique=True)),
                ('observation_start', models.DateField()),
                ('observation_end', models.DateField()),
                ('frequency', models.CharField(max_length=50)),
                ('units', models.CharField(max_length=100)),
                ('seasonal_adjustment', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('data_type', models.CharField(choices=[('economic', 'Economic'), ('financial', 'Financial')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CorporateBondSpread',
            fields=[
                ('dataseries_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.dataseries')),
            ],
            bases=('dashboard.dataseries',),
        ),
        migrations.CreateModel(
            name='FedFundsRate',
            fields=[
                ('dataseries_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.dataseries')),
            ],
            bases=('dashboard.dataseries',),
        ),
        migrations.CreateModel(
            name='ISMManufacturing',
            fields=[
                ('dataseries_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.dataseries')),
            ],
            bases=('dashboard.dataseries',),
        ),
        migrations.CreateModel(
            name='ISMServices',
            fields=[
                ('dataseries_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.dataseries')),
            ],
            bases=('dashboard.dataseries',),
        ),
        migrations.CreateModel(
            name='NominalInflation',
            fields=[
                ('dataseries_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.dataseries')),
            ],
            bases=('dashboard.dataseries',),
        ),
        migrations.CreateModel(
            name='RealGDP',
            fields=[
                ('dataseries_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.dataseries')),
            ],
            bases=('dashboard.dataseries',),
        ),
        migrations.CreateModel(
            name='RealInterestRate',
            fields=[
                ('dataseries_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.dataseries')),
            ],
            bases=('dashboard.dataseries',),
        ),
        migrations.CreateModel(
            name='Sp500',
            fields=[
                ('dataseries_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.dataseries')),
            ],
            bases=('dashboard.dataseries',),
        ),
        migrations.CreateModel(
            name='TreasuryYield',
            fields=[
                ('dataseries_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.dataseries')),
            ],
            bases=('dashboard.dataseries',),
        ),
        migrations.CreateModel(
            name='VIX',
            fields=[
                ('dataseries_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.dataseries')),
            ],
            bases=('dashboard.dataseries',),
        ),
        migrations.CreateModel(
            name='EconomicDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economic_data_points', to='dashboard.dataseries')),
            ],
            options={
                'db_table': 'economic_data_point',
                'get_latest_by': 'date',
                'unique_together': {('series', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FinancialDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_data_points', to='dashboard.dataseries')),
            ],
            options={
                'db_table': 'financial_data_point',
                'get_latest_by': 'date',
                'unique_together': {('series', 'date')},
            },
        ),
    ]
