# Generated by Django 5.1 on 2024-10-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataseries',
            name='observation_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataseries',
            name='observation_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
