# Generated by Django 5.1 on 2024-10-17 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_dataseries_observation_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataseries',
            name='data_type',
        ),
    ]
