# Generated by Django 5.1 on 2024-10-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_dataseries_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataseries',
            name='data_type',
            field=models.CharField(choices=[('economic', 'Economic'), ('financial', 'Financial')], default='financial', max_length=10),
            preserve_default=False,
        ),
    ]
