# Generated by Django 5.1 on 2024-10-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dataseries_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataseries',
            name='data_origin',
            field=models.CharField(choices=[('fred', 'FRED'), ('polygon', 'Polygon.io')], default='polygon', max_length=20),
            preserve_default=False,
        ),
    ]
