# Generated by Django 5.1 on 2025-01-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_dataseries_data_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataseries',
            name='frequency',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dataseries',
            name='series_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
