# Generated by Django 5.1 on 2025-01-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_dataseries_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataseries',
            name='frequency',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='dataseries',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='dataseries',
            name='seasonal_adjustment',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='dataseries',
            name='series_id',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='dataseries',
            name='units',
            field=models.CharField(max_length=150),
        ),
    ]
