# Generated by Django 5.1 on 2025-01-06 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_dataseries_frequency_alter_dataseries_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='economicdatapoint',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='economicdatapoint',
            name='series',
        ),
        migrations.RemoveField(
            model_name='fedfundsrate',
            name='dataseries_ptr',
        ),
        migrations.AlterUniqueTogether(
            name='financialdatapoint',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='financialdatapoint',
            name='series',
        ),
        migrations.RemoveField(
            model_name='ismmanufacturing',
            name='dataseries_ptr',
        ),
        migrations.RemoveField(
            model_name='ismservices',
            name='dataseries_ptr',
        ),
        migrations.RemoveField(
            model_name='nominalinflation',
            name='dataseries_ptr',
        ),
        migrations.RemoveField(
            model_name='realgdp',
            name='dataseries_ptr',
        ),
        migrations.RemoveField(
            model_name='realinterestrate',
            name='dataseries_ptr',
        ),
        migrations.RemoveField(
            model_name='sp500',
            name='dataseries_ptr',
        ),
        migrations.RemoveField(
            model_name='treasuryyield',
            name='dataseries_ptr',
        ),
        migrations.RemoveField(
            model_name='vix',
            name='dataseries_ptr',
        ),
        migrations.DeleteModel(
            name='CorporateBondSpread',
        ),
        migrations.DeleteModel(
            name='EconomicDataPoint',
        ),
        migrations.DeleteModel(
            name='FedFundsRate',
        ),
        migrations.DeleteModel(
            name='FinancialDataPoint',
        ),
        migrations.DeleteModel(
            name='ISMManufacturing',
        ),
        migrations.DeleteModel(
            name='ISMServices',
        ),
        migrations.DeleteModel(
            name='NominalInflation',
        ),
        migrations.DeleteModel(
            name='RealGDP',
        ),
        migrations.DeleteModel(
            name='RealInterestRate',
        ),
        migrations.DeleteModel(
            name='Sp500',
        ),
        migrations.DeleteModel(
            name='TreasuryYield',
        ),
        migrations.DeleteModel(
            name='VIX',
        ),
    ]
