# Generated by Django 5.1 on 2025-02-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_economicdatapoint_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataseries',
            name='last_data_date',
            field=models.DateField(blank=True, help_text='Date of the most recent data point in the time series.', null=True),
        ),
    ]
