# Generated by Django 5.1 on 2024-09-06 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcreteDataSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('series_id', models.CharField(max_length=50, unique=True)),
                ('observation_start', models.DateField()),
                ('observation_end', models.DateField()),
                ('frequency', models.CharField(max_length=50)),
                ('units', models.CharField(max_length=100)),
                ('seasonal_adjustment', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CorporateBondSpread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('series_id', models.CharField(max_length=50, unique=True)),
                ('observation_start', models.DateField()),
                ('observation_end', models.DateField()),
                ('frequency', models.CharField(max_length=50)),
                ('units', models.CharField(max_length=100)),
                ('seasonal_adjustment', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FedFundsRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('series_id', models.CharField(max_length=50, unique=True)),
                ('observation_start', models.DateField()),
                ('observation_end', models.DateField()),
                ('frequency', models.CharField(max_length=50)),
                ('units', models.CharField(max_length=100)),
                ('seasonal_adjustment', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ISMManufacturing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('series_id', models.CharField(max_length=50, unique=True)),
                ('observation_start', models.DateField()),
                ('observation_end', models.DateField()),
                ('frequency', models.CharField(max_length=50)),
                ('units', models.CharField(max_length=100)),
                ('seasonal_adjustment', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ISMServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('series_id', models.CharField(max_length=50, unique=True)),
                ('observation_start', models.DateField()),
                ('observation_end', models.DateField()),
                ('frequency', models.CharField(max_length=50)),
                ('units', models.CharField(max_length=100)),
                ('seasonal_adjustment', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NominalInflation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('series_id', models.CharField(max_length=50, unique=True)),
                ('observation_start', models.DateField()),
                ('observation_end', models.DateField()),
                ('frequency', models.CharField(max_length=50)),
                ('units', models.CharField(max_length=100)),
                ('seasonal_adjustment', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RealGDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('series_id', models.CharField(max_length=50, unique=True)),
                ('observation_start', models.DateField()),
                ('observation_end', models.DateField()),
                ('frequency', models.CharField(max_length=50)),
                ('units', models.CharField(max_length=100)),
                ('seasonal_adjustment', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RealInterestRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('series_id', models.CharField(max_length=50, unique=True)),
                ('observation_start', models.DateField()),
                ('observation_end', models.DateField()),
                ('frequency', models.CharField(max_length=50)),
                ('units', models.CharField(max_length=100)),
                ('seasonal_adjustment', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sp500',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('series_id', models.CharField(max_length=50, unique=True)),
                ('observation_start', models.DateField()),
                ('observation_end', models.DateField()),
                ('frequency', models.CharField(max_length=50)),
                ('units', models.CharField(max_length=100)),
                ('seasonal_adjustment', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TreasuryYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('series_id', models.CharField(max_length=50, unique=True)),
                ('observation_start', models.DateField()),
                ('observation_end', models.DateField()),
                ('frequency', models.CharField(max_length=50)),
                ('units', models.CharField(max_length=100)),
                ('seasonal_adjustment', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VIX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('series_id', models.CharField(max_length=50, unique=True)),
                ('observation_start', models.DateField()),
                ('observation_end', models.DateField()),
                ('frequency', models.CharField(max_length=50)),
                ('units', models.CharField(max_length=100)),
                ('seasonal_adjustment', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
